# Generated by Django 3.2 on 2022-11-21 11:33

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_followings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default8.jpg', upload_to='profile/%Y/%m'),
        ),
    ]
